name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - uses: gradle/actions/wrapper-validation@v4
      - run: chmod +x ./gradlew
      - run: ./gradlew build check connectedAndroidTest --no-daemon
        env:
          ORG_GRADLE_PROJECT_githubSignerryUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubSignerryPassword: ${{ github.token }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: "**/build/reports/**/*"
          retention-days: 7
