name: Release
on:
  - workflow_dispatch
  - push

permissions:
  contents: read
  packages: read
  id-token: write
  attestations: write

jobs:
  build-mobile-release-apk:
    name: Build Mobile Release APK
    runs-on: ubuntu-latest
    environment: production
    env:
      ORG_GRADLE_PROJECT_githubSignerryUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubSignerryPassword: ${{ github.token }}
      ORG_GRADLE_PROJECT_storeFile: "${{ github.workspace }}/upload-keystore.jks"
      ORG_GRADLE_PROJECT_storePassword: ${{ secrets.STORE_PASSWORD }}
      ORG_GRADLE_PROJECT_keyAlias: ${{ vars.KEY_ALIAS }}
      ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - uses: gradle/actions/wrapper-validation@v4
      - run: chmod +x ./gradlew
      - run: echo $STORE_FILE | base64 -d > $ORG_GRADLE_PROJECT_storeFile
        env:
          STORE_FILE: ${{ secrets.STORE_FILE }}
      - run: ./gradlew :mobile:build
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: "mobile/build/outputs/apk/release/mobile-release.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: mobile-release-apk
          path: "mobile/build/outputs/apk/release/mobile-release.apk"
          retention-days: 14
